angular.module('angularWistia', ['ui.bootstrap', 'ui.utils', 'ngRoute', 'ngAnimate']);

angular.module('angularWistia').config(function ($routeProvider) {

    /* Add New Routes Above */
    $routeProvider.otherwise({redirectTo: '/home'});

});

angular.module('angularWistia').run(function ($rootScope) {
    // generated by yo
    $rootScope.safeApply = function (fn) {
        var phase = $rootScope.$$phase;
        if (phase === '$apply' || phase === '$digest') {
            if (fn && (typeof(fn) === 'function')) {
                fn();
            }
        } else {
            this.$apply(fn);
        }
    };
});
